# Use Node.js v14
FROM node:14

# Create app directory
WORKDIR /app

COPY package*.json ./

RUN npm install

# Bundle app source
COPY . .

# Expose the port

EXPOSE 3000
EXPOSE 3000

CMD [ "node", "server.js" ]
